version: "3.7"

services:
  edsm_2_frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
